# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stockCalculation.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StockRiskCalculator(object):
    def setupUi(self, StockRiskCalculator):
        StockRiskCalculator.setObjectName("StockRiskCalculator")
        StockRiskCalculator.resize(941, 335)
        self.centralwidget = QtWidgets.QWidget(StockRiskCalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.search_le = QtWidgets.QLineEdit(self.frame)
        self.search_le.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.search_le.setObjectName("search_le")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 131, 221))
        self.listWidget.setObjectName("listWidget")
        self.right_pb = QtWidgets.QPushButton(self.frame)
        self.right_pb.setGeometry(QtCore.QRect(150, 130, 31, 23))
        self.right_pb.setObjectName("right_pb")
        self.left_pb = QtWidgets.QPushButton(self.frame)
        self.left_pb.setGeometry(QtCore.QRect(150, 160, 31, 23))
        self.left_pb.setObjectName("left_pb")
        self.listWidget_2 = QtWidgets.QListWidget(self.frame)
        self.listWidget_2.setGeometry(QtCore.QRect(190, 40, 131, 221))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 0, 311, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(190, 20, 101, 16))
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(334, 124, 144, 137))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.up_pb = QtWidgets.QPushButton(self.layoutWidget)
        self.up_pb.setObjectName("up_pb")
        self.verticalLayout.addWidget(self.up_pb)
        self.down_pb = QtWidgets.QPushButton(self.layoutWidget)
        self.down_pb.setObjectName("down_pb")
        self.verticalLayout.addWidget(self.down_pb)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.start_date = QtWidgets.QDateEdit(self.layoutWidget)
        self.start_date.setObjectName("start_date")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.start_date)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.end_date = QtWidgets.QDateEdit(self.layoutWidget)
        self.end_date.setObjectName("end_date")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.end_date)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(337, 40, 61, 16))
        self.label_5.setObjectName("label_5")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QtCore.QRect(426, 40, 51, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setStyleSheet("color: rgb(0, 0, 0);")
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(337, 80, 81, 16))
        self.label_6.setObjectName("label_6")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_2.setGeometry(QtCore.QRect(426, 80, 51, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.lcdNumber_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.tableView = QtWidgets.QTableView(self.frame)
        self.tableView.setGeometry(QtCore.QRect(490, 90, 421, 171))
        self.tableView.setObjectName("tableView")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(490, 70, 201, 16))
        self.label_7.setObjectName("label_7")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(490, 10, 421, 61))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.expected_return_le = QtWidgets.QLineEdit(self.groupBox)
        self.expected_return_le.setObjectName("expected_return_le")
        self.horizontalLayout.addWidget(self.expected_return_le)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.portfolio_risk_le = QtWidgets.QLineEdit(self.groupBox)
        self.portfolio_risk_le.setObjectName("portfolio_risk_le")
        self.horizontalLayout.addWidget(self.portfolio_risk_le)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        StockRiskCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StockRiskCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 21))
        self.menubar.setObjectName("menubar")
        self.menuQuit = QtWidgets.QMenu(self.menubar)
        self.menuQuit.setObjectName("menuQuit")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        StockRiskCalculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StockRiskCalculator)
        self.statusbar.setObjectName("statusbar")
        StockRiskCalculator.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(StockRiskCalculator)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(StockRiskCalculator)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_Qt = QtWidgets.QAction(StockRiskCalculator)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.menuQuit.addAction(self.actionExit)
        self.menubar.addAction(self.menuQuit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(StockRiskCalculator)
        self.actionExit.triggered.connect(StockRiskCalculator.close)
        self.pushButton.clicked['bool'].connect(self.pushButton.toggle)
        QtCore.QMetaObject.connectSlotsByName(StockRiskCalculator)

    def retranslateUi(self, StockRiskCalculator):
        _translate = QtCore.QCoreApplication.translate
        StockRiskCalculator.setWindowTitle(_translate("StockRiskCalculator", "Stock Risk and Return Calculator"))
        self.right_pb.setText(_translate("StockRiskCalculator", ">"))
        self.left_pb.setText(_translate("StockRiskCalculator", "<"))
        self.label.setText(_translate("StockRiskCalculator", "Search and Select Stocks"))
        self.label_2.setText(_translate("StockRiskCalculator", "Selected Stocks"))
        self.up_pb.setText(_translate("StockRiskCalculator", "Up"))
        self.down_pb.setText(_translate("StockRiskCalculator", "Down"))
        self.label_3.setText(_translate("StockRiskCalculator", "Start_Date"))
        self.label_4.setText(_translate("StockRiskCalculator", "End_Date"))
        self.pushButton.setText(_translate("StockRiskCalculator", "Calculate Risk"))
        self.label_5.setText(_translate("StockRiskCalculator", "No of Stocks"))
        self.label_6.setText(_translate("StockRiskCalculator", "Selected Stocks"))
        self.label_7.setText(_translate("StockRiskCalculator", "Calculated Final Weights for Portfolio"))
        self.groupBox.setTitle(_translate("StockRiskCalculator", "Expected Return and Risk"))
        self.label_8.setText(_translate("StockRiskCalculator", "Annual Return"))
        self.label_9.setText(_translate("StockRiskCalculator", "Portfolio Risk"))
        self.menuQuit.setTitle(_translate("StockRiskCalculator", "File"))
        self.menuAbout.setTitle(_translate("StockRiskCalculator", "Help"))
        self.actionExit.setText(_translate("StockRiskCalculator", "Exit"))
        self.actionAbout.setText(_translate("StockRiskCalculator", "About"))
        self.actionAbout.setStatusTip(_translate("StockRiskCalculator", "\"Show the application\'s About box\""))
        self.actionAbout_Qt.setText(_translate("StockRiskCalculator", "About-Qt"))
        self.actionAbout_Qt.setStatusTip(_translate("StockRiskCalculator", "\"Show the Qt library\'s About box\""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StockRiskCalculator = QtWidgets.QMainWindow()
    ui = Ui_StockRiskCalculator()
    ui.setupUi(StockRiskCalculator)
    StockRiskCalculator.show()
    sys.exit(app.exec_())
